name: gsimarvelitas
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+4
  dio: 1.0.0
  google_fonts: ^0.3.9


  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  font_awesome_flutter: ^8.0.1

flutter:

  uses-material-design: true

  assets:
      - assets/login_logo.png
      - assets/ajustes.png
      - assets/msmarvel1.jpg
      - assets/shehulk1.jpg
      - assets/mightythor1.jpg
      - assets/dicaprio.jpg
      - assets/login.jpg
      - assets/background.jpg

  fonts:
    - family: MyFlutterApp
      fonts: 
        - asset: assets/fonts/MyFlutterApp/MyFlutterApp.ttf
    - family: WorkSansSemiBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf

    - family: WorkSansBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf
        