name: gsimarvelitas
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+4
  dio: 1.0.0
  google_fonts: ^0.3.9


  cupertino_icons: ^0.1.2
  flutter_bloc: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  font_awesome_flutter: ^8.0.1
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/login_logo.png"

flutter:

  uses-material-design: true

  assets:
      - assets/login_logo.png
      - assets/ajustes.png
      - assets/mightythor1.jpg
      - assets/dicaprio.jpg
      - assets/login.jpg
      - assets/background.jpg
      - assets/wallpaper.jpg
      - assets/wallpaper1.jpg
      - assets/carol.jpg
      - assets/fondo_perfil1.jpg
      - assets/goose.jpg
      - assets/hulka.jpg
      - assets/hulka2.jpg
      - assets/spaiderman.jpg
      - assets/spaidermangris.jpg

  fonts:
    - family: MyFlutterApp
      fonts: 
        - asset: assets/fonts/MyFlutterApp/MyFlutterApp.ttf
    - family: WorkSansSemiBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-SemiBold.ttf

    - family: WorkSansBold
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Bold.ttf

    - family: WorkSansMedium
      fonts:
        - asset: assets/fonts/Work_Sans/WorkSans-Medium.ttf
        